name: gabrielcamelo
favicon: null
layout_spectrum: 0.2527008776087314
typography_spectrum: 0.7387209618464112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4907994535751641
  lightness: 0.5751808127388358
  saturation: 0.40197741240262985
  rhythmicContrast: 0.21711969701573253
purpose: []
